# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-10 12:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenerys', '0003_auto_20190909_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='景区名称')),
                ('detail', models.TextField(verbose_name='详情')),
                ('image', models.ImageField(upload_to='scenerys/%Y/%m', verbose_name='封面图')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_index', models.BooleanField(default=0, verbose_name='是否首页')),
                ('guide_sce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenerys.Scenerys', verbose_name='景区攻略')),
            ],
            options={
                'verbose_name': '攻略',
                'verbose_name_plural': '攻略',
            },
        ),
    ]
