# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-09 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='省份')),
                ('image', models.ImageField(upload_to='provinces/%Y/%m', verbose_name='封面图')),
                ('click_nums', models.ImageField(default=0, upload_to='', verbose_name='点击数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.CharField(choices=[('hz', '华中'), ('hb', '华北'), ('hd', '华东'), ('hn', '华南'), ('xb', '西北'), ('db', '东北'), ('xn', '西南')], default='hz', max_length=20, verbose_name='地区')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
    ]
