# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0002_auto_20190909_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinces',
            name='eng_name',
            field=models.CharField(max_length=50, null=True, verbose_name='省份英文'),
        ),
    ]
