# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-09 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='景区名称')),
                ('desc', models.CharField(max_length=300, verbose_name='简介')),
                ('detail', models.TextField(verbose_name='详情')),
                ('image', models.ImageField(upload_to='scenerys/%Y/%m', verbose_name='封面图')),
                ('click_nums', models.ImageField(default=0, upload_to='', verbose_name='点击数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '景区',
                'verbose_name_plural': '景区',
            },
        ),
    ]
