# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-09 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenerys', '0002_scenerys_scen_prov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenerys',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
